OBJS := \
    ucs-2.o \
    us-ascii.o \
    cesbi.o \
    utf-16.o \
    ucs-4.o \
    ucs-2-internal.o \
    table-pcs.o \
    utf-8.o \
    euc.o \
    ucs-4-internal.o \
    table.o

DIR := iconv/ces
LEVEL := ../..
include ${LEVEL}/Makefile.common
