OBJS := \
    bsearch.o \
    hash_bigkey.o \
    hash_buf.o \
    hash.o \
    hash_func.o \
    hash_log2.o \
    hash_page.o \
    hcreate.o \
    hcreate_r.o \
    qsort.o \
    tdelete.o \
    tdestroy.o \
    tfind.o \
    tsearch.o \
    twalk.o

DIR := search
LEVEL := ..
include ${LEVEL}/Makefile.common
