OBJS := \
    argz_add.o \
    argz_add_sep.o \
    argz_append.o \
    argz_count.o \
    argz_create.o \
    argz_create_sep.o \
    argz_delete.o \
    argz_extract.o \
    argz_insert.o \
    argz_next.o \
    argz_replace.o \
    argz_stringify.o \
    buf_findstr.o \
    dummy.o \
    envz_add.o \
    envz_entry.o \
    envz_get.o \
    envz_merge.o \
    envz_remove.o \
    envz_strip.o

DIR := argz
LEVEL := ..
include ${LEVEL}/Makefile.common
