OBJS := \
    fix_grouping.o \
    ldpart.o \
    lmessages.o \
    lmonetary.o \
    lnumeric.o \
    locale.o \
    nl_langinfo.o \
    timelocal.o

DIR := locale
LEVEL := ..
include ${LEVEL}/Makefile.common
