OBJS := \
    ctype_.o \
    isalnum.o \
    isalpha.o \
    isascii.o \
    isblank.o \
    iscntrl.o \
    isdigit.o \
    islower.o \
    isprint.o \
    ispunct.o \
    isspace.o \
    isupper.o \
    iswalnum.o \
    iswalpha.o \
    iswblank.o \
    iswcntrl.o \
    iswctype.o \
    iswdigit.o \
    iswgraph.o \
    iswlower.o \
    iswprint.o \
    iswpunct.o \
    iswspace.o \
    iswupper.o \
    iswxdigit.o \
    isxdigit.o \
    jp2uc.o \
    toascii.o \
    _tolower.o \
    tolower.o \
    _toupper.o \
    toupper.o \
    towctrans.o \
    towlower.o \
    towupper.o \
    wctrans.o \
    wctype.o

DIR := ctype
LEVEL := ..
include ${LEVEL}/Makefile.common
