OBJS := \
    asctime.o \
    asctime_r.o \
    clock.o \
    ctime.o \
    ctime_r.o \
    difftime.o \
    gettzinfo.o \
    gmtime.o \
    gmtime_r.o \
    lcltime.o \
    lcltime_r.o \
    mktime.o \
    mktm_r.o \
    strftime.o \
    strptime.o \
    time.o \
    tzlock.o \
    tzset.o \
    tzset_r.o \
    tzvars.o

DIR := time
LEVEL := ..
include ${LEVEL}/Makefile.common
