OBJS := \
    koi8_r.o \
    win_1250.o \
    iso_8859_8.o \
    win_1258.o \
    koi8_uni.o \
    iso_8859_2.o \
    cp775.o \
    iso_8859_9.o \
    ccsbi.o \
    jis_x0212_1990.o \
    jis_x0208_1990.o \
    cp850.o \
    big5.o \
    iso_8859_7.o \
    iso_8859_1.o \
    win_1255.o \
    iso_8859_4.o \
    iso_8859_5.o \
    cns11643_plane14.o \
    cns11643_plane2.o \
    win_1254.o \
    win_1256.o \
    iso_ir_111.o \
    cns11643_plane1.o \
    koi8_u.o \
    win_1253.o \
    ksx1001.o \
    iso_8859_14.o \
    iso_8859_15.o \
    cp866.o \
    win_1251.o \
    win_1252.o \
    win_1257.o \
    jis_x0201_1976.o \
    cp855.o \
    iso_8859_3.o \
    iso_8859_6.o \
    koi8_ru.o \
    iso_8859_10.o \
    iso_8859_11.o \
    cp852.o \
    iso_8859_13.o

DIR := iconv/ccs
LEVEL := ../..
include ${LEVEL}/Makefile.common
