OBJS := \
    closer.o \
    execr.o \
    fcntlr.o \
    fstatr.o \
    getreent.o \
    gettimeofdayr.o \
    impure.o \
    isattyr.o \
    linkr.o \
    lseekr.o \
    openr.o \
    readr.o \
    reent.o \
    renamer.o \
    sbrkr.o \
    signalr.o \
    signgam.o \
    statr.o \
    timesr.o \
    unlinkr.o \
    writer.o

DIR := reent
LEVEL := ..
include ${LEVEL}/Makefile.common
